sudo: false
language: node_js
node_js:
- '0.10'

services:
  - mongodb

cache:
  directories:
    - node_modules

before_install:
- export PATH=$HOME/.local/bin:${PATH}

install: pip install --user boto

install:
- npm install

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: npm test

notifications:
  email:
    - ivar.prudnikov@gmail.com
  on_success: always
  on_failure: always
